FROM node:16-alpine3.12

LABEL version="1.0"
LABEL description="React Frontend for the Real Estate API"

WORKDIR /app

COPY ./package*.json ./

RUN npm install

RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache

RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object

COPY . .
CMD [ "npm", "run", "start"]