# Generated by Django 5.0.1 on 2024-02-03 17:48

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'pkid',
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'phone_number',
                    phonenumber_field.modelfields.PhoneNumberField(
                        default='+5514999999999',
                        max_length=30,
                        region=None,
                        verbose_name='Phone Number',
                    ),
                ),
                (
                    'about_me',
                    models.TextField(
                        default='Say something about yourself',
                        verbose_name='About me',
                    ),
                ),
                (
                    'license',
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name='Real Estate license',
                    ),
                ),
                (
                    'profile_photo',
                    models.ImageField(
                        default='/profile_default.png',
                        upload_to='',
                        verbose_name='Profile Photo',
                    ),
                ),
                (
                    'gender',
                    models.CharField(
                        choices=[
                            ('Male', 'Male'),
                            ('Female', 'Female'),
                            ('Other', 'Other'),
                        ],
                        default='Other',
                        verbose_name='Gender',
                    ),
                ),
                (
                    'country',
                    django_countries.fields.CountryField(
                        default='KE', max_length=2, verbose_name='Country'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
