# Generated by Django 5.0.1 on 2024-02-03 22:48

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_city_profile_is_agent_profile_is_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='Diga algo sobre você', verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='São Paulo', max_length=180, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='BRL', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Licença imobiliária'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+55(14) 9 9999-9999', max_length=30, region=None, verbose_name='Phone Number'),
        ),
    ]
