# Generated by Django 5.0.1 on 2024-02-04 09:21

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'profiles',
            '0003_alter_profile_about_me_alter_profile_city_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(
                default='BR', max_length=2, verbose_name='Country'
            ),
        ),
    ]
