# Generated by Django 5.0.1 on 2024-02-10 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_number',
            field=models.IntegerField(default=112, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Property Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='KG8 Avenue', max_length=150, verbose_name='Street Address'),
        ),
    ]
