# Generated by Django 5.0.1 on 2024-02-13 16:00

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_property_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(
                default=apps.users.models.User,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='agent_buyer',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Agente, Seller or Buyer',
            ),
        ),
    ]
