# Generated by Django 5.0.1 on 2024-02-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
    ]
